### PR TITLE
Add information about canary_selection_params for upgrade errand

### PR DESCRIPTION
**Pull request by terminatingcode**
[#154212179]

### CODE REVIEW

**Comment by deniseyu** [comment]
Approved

**Comment by deniseyu** [comment]
Please merge into master only

**Comment by jncd** [comment]
Thanks @terminatingcode and @deniseyu !

**Comment by jncd** [comment]
FYI: I'm going to change
>`canary_selection_params` can be used to specify the specific org and space desired to source service instances to be used as canaries in an upgrade operation."
to 
> Use `canary_selection_params` to specify the org and space that you want canaries to be sourced from during an upgrade. 

Let me know if I haven't preserved your meaning.
@terminatingcode and @deniseyu

**Comment by terminatingcode** [comment]
Thanks @jncd.
The only thing is that the wording sounds to me like the selection params are required but they are optional. Is there a way of phrasing it so that it feels less prescriptive?

**Comment by jncd** [comment]
Aha, this is good to understand! So, our standard convention is to write: 
> (Optional) Use `canary_selection_params` to specify an org and a space that you want canaries to be sourced from during an upgrade.

**Pull request merged**
