### PR TITLE
Schemas validation docs

### PR DESCRIPTION
**Pull request by nodo**
[#155254067]

Signed-off-by: Derik Evangelista <devangelista@pivotal.io>

### CODE REVIEW

**Comment by deniseyu** [comment]
Approved

**Comment by deniseyu** [comment]
@nodo please can you fix the link text to say OSBAPI 2.13 not 2.12

**Comment by deniseyu** [comment]
SORRY not approved yet! pending that fix :-)

**Comment by kieron-pivotal** [comment]
@deniseyu @nodo I've pushed the 2.12->2.13 fix

**Comment by deniseyu** [comment]
Approved

**Comment by deniseyu** [comment]
Please merge into master only

**Comment by ghanna2017** [comment]
Thanks @nodo @deniseyu

**Pull request merged**
