### PR TITLE
Docs for canary_selection_params in Service Instances API

### PR DESCRIPTION
**Pull request by nodo**
[#154328039]

Signed-off-by: Andrea Nodari <anodari@pivotal.io>

### CODE REVIEW

**Comment by deniseyu** [comment]
Approved

**Comment by deniseyu** [comment]
@ghanna2017 @snneji please merge into master only. Please also have a look at minor grammar issues - let me know if you'd like us to fix.

**Comment by ghanna2017** [comment]
Thanks @nodo @deniseyu

**Comment by jncd** [comment]
Hi Denise, @deniseyu and @nodo 

I did a light copyedit in a branch. Would you take a look at it before I merge it? 
I found the text a little unclear. 

For example, 
> "the service-instances API needs to be changed accordingly."
Who needs to do this? Can I say:
> "you need to change the Service Instances API accordingly."

I guessed a missing word or two. You should be able to compare the master branch and the PR-31-155896640 branch to see the changes.

For new content, we have to keep the lines shorter, never more than one sentence per line with a goal of ~80 characters. So, you'll see I broke up some of the longest ones.

Reach out in your afternoon if you have questions. We're only 7 hours apart this week.

screen shot 2018-03-13 at 2 59 45 pm

**Comment by nodo** [comment]
@jncd Thanks a lot! Looks good to me 👍

**Comment by jncd** [comment]
Hi @nodo 
Thanks for checking this over. (I gave it my best guesses.)
I'll merge in this edit and now.

**Pull request merged**
