### PR TITLE
release notes for 0.26.1

### PR DESCRIPTION
**Pull request by kieron-pivotal**
Hi, please see release notes for a patch against ODB-0.26

### CODE REVIEW

**Comment by snneji** [comment]
Hi @kieron-pivotal this PR should be on the v0.26.x branch. Could you submit a PR there please? 

We usually stack patches on top of each other like in the example here: https://docs-wiki.cfapps.io/wiki/style/release-notes.html#example.
Thanks!

**Comment by jncd** [comment]
I'm struggling to understand the Resolved Issue text.
screen shot 2019-02-22 at 3 52 06 pm
The bullet doesn't follow well after the intro sentence.

I think that all of "~~Bumped the On Demand Services SDK to integrate a change where~~" should be deleted and just the issue itself needs to be stated.  Is the issue listed as a known issue elsewhere? If not, should it be?

What was the issue? How would I know if I'd experienced it? Was it that "`delete_binding` failed in environments using BOSH DNS addresses"?  

Would it be helpful to cross-reference delete_binding part of the doc : http://docs-pcf-staging.cfapps.io/svc-sdk/odb/0-26/adapter-reference.html#delete-binding

**Comment by kieron-pivotal** [comment]
The issue with v0.26.0 is that we didn't tag the correct version of the on-demand-services-sdk which ships with the on-demand-broker. This means teams using this library would get a version missing the new parameter passed into the DeleteBinding method.
 
v0.26.1 tags the correct version of on-demand-services-sdk resolving this.

Should we add this to the known issues of 0.26.0 and then refer to that in 0.26.1?

**Comment by jncd** [comment]
I think that would be best. That way, if anyone has downloaded the 0.26.0, they'll know of the problem.
It makes an honest pattern—have a known issue => fix a known issue.

**Pull request closed without merging**
