### PR TITLE
Add warning about modifying ODB managed secrets

### PR DESCRIPTION
**Pull request by jacknewberry**
[#160089418]

Co-authored-by: Derik Evangelista <devangelista@pivotal.io>

### CODE REVIEW

**Comment by ghanna2017** [comment]
@ruthmaclean Hi Ruth, are you able to approve these through github now? Do you still want to keep the approval process?

**Comment by ruthmaclean** [comment]
@ghanna2017 I'm happy to merge these by myself if you are?

**Comment by ghanna2017** [comment]
Hey @ruthmaclean please don't merge these since it's part of our process and that's how we know we have something to edit. (Also, sometimes it doesn't enter our backlog correctly - as in this case - so it breaks how we know we've edited something or not). Thanks!

**Comment by ruthmaclean** [comment]
@snneji please can you let us know what your questions are on this change?

**Pull request merged**
