### PR TITLE
Document "disabled" lifecycle errand property

### PR DESCRIPTION
**Pull request by chewymeister**
[#158290562]

### CODE REVIEW

**Comment by ruthmaclean** [comment]
approved

**Comment by ruthmaclean** [comment]
please merge to master @pivotal-cf/docs

**Comment by ghanna2017** [comment]
Hey @ruthmaclean , this repo is set up for PMs to approve PRs before we merge them. Not sure how you do that on your end (see the "Some checks haven't completed yet" message above). 

You can also remove that extra check if you don't think it's needed anymore.

**Comment by snneji** [comment]
@ruthmaclean @ghanna I think the "Some checks haven't been completed" message is still there because you were added to the pull approve list after this PR was submitted. Apparently it doesn't automatically update existing PRs. Pull approve will probably work for PRs submitted in the future.

**Pull request merged**
