### PR TITLE
Add documentation for 0.27.0 release

### PR DESCRIPTION
**Pull request by winnab**
- support for multi-stemcells

[#164954639]

Co-authored-by: Derik Evangelista <devangelista@pivotal.io>

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @winnab 
Looks like you're ready to release on Friday!

**Comment by jncd** [comment]
@winnab 
Also noticed references to `ubuntu-trusty` — since we've moved to xenial, should these be changed?

**Comment by jncd** [comment]
Hi @winnab 

This new feature sounds pretty nifty. Can you say a little more about it in the release notes? For example change:

> The on-demand broker (ODB) now supports service instance deployments that use different stemcells for different instance groups.

to something like:

> The on-demand broker (ODB) now allows service instance deployments to use different stemcells for different instance groups. For example, one service plan can use Windows stemcells and another plan can use Xenial stemcells. For more information, see [best link for how to add multiple stemcells]. 

What is the most likey use case for an array of stemcells? Is it to support Windows and Ubuntu together? or to help with the Trusty to Xenial transition? 

The release notes say it can be done, but it would be kind to add a link the main doc that tells the reader how it can be done? Is it all done in [SERVICE-DEPLOYMENT-JSON](http://docs-pcf-staging.cfapps.io/svc-sdk/odb/0-2n/adapter-reference.html#generate-manifest-parameters) ? 

Just for my own understanding... is an instance group like all instances created by a particular plan type? or can I have instances created by the same plan-type but using different stemcells? 
How would end-users indicate that they wanted to use one stemcell type over another.

**Comment by winnab** [comment]
> @winnab
> Also noticed references to `ubuntu-trusty` — since we've moved to xenial, should these be changed?

Sure, these can be changed.

**Comment by winnab** [comment]
Maybe we can say:

> The on-demand broker (ODB) now allows service instance deployments to use different stemcells for different instance groups. For example, one service plan can use both a Windows and Xenial stemcell. To use multiple stemcells, define the stemcell list in the `service_deployment` section of your broker manifest. For more information, see [Starter Snippet for the Service Catalog and Plans](http://docs-pcf-staging.cfapps.io/svc-sdk/odb/0-2n/operating.html#catalog).

------------

> What is the most likely use case for an array of stemcells? Is it to support Windows and Ubuntu together? or to help with the Trusty to Xenial transition?

The reason we implemented this when we did was because PKS wants to add Windows support, and to do that they need VMs that use Windows and Ubuntu stemcells. 

> The release notes say it can be done, but it would be kind to add a link the main doc that tells the reader how it can be done? Is it all done in SERVICE-DEPLOYMENT-JSON?

I've added a link in the first block at the top of this comment. The `SERVICE-DEPLOYMENT-JSON` is really just internal between the broker and the adapter. The user needs to configure the broker manifest's `service_deployment` to take advantage of the feature.

> Just for my own understanding... is an instance group like all instances created by a particular plan type? or can I have instances created by the same plan-type but using different stemcells?

Instance groups are a [BOSH concept](https://bosh.io/docs/manifest-v2/#instance-groups).

> How would end-users indicate that they wanted to use one stemcell type over another.

This is up to the service instance deployment manifest that the adapter generates and gives to the broker.

**Pull request merged**
